Taka005/TakasumiBOTv2

lang/en.json
lang/ja.json
module/event/ready/command.js
module/event/ready/status.js
module/function/slashcommand/5000.js
module/function/slashcommand/global.js
module/function/slashcommand/hiroyuki.js
module/function/slashcommand/setting.js
module/lib/lang.js
package-lock.json
package.json

少し英語に対応、v14への対応

---

module/lib/count.js
module/lib/db.js

データベースでプールをプールを使用するように

---

module/event/messageCreate/pin.js
module/function/slashcommand/status.js
module/lib/sign.js

- sign関数追加
- pinのawait追加
- ステータスを調整

fix:await追加、その他調整

---

file/commandlist.json
lang/ja.json
module/function/slashcommand/account.js

change:翻訳を追加・その他調整

---

lang/ja.json
module/event/interactionCreate/script.js
module/function/slashcommand/snowflake.js

- snowflakeを改善
- バグを調整
- 翻訳を追加

バグを修正・翻訳追加

---

lang/ja.json
module/event/interactionCreate/script.js
module/function/slashcommand/snowflake.js

パッケージのアップデート

---

file/commandlist.json
lang/ja.json
module/event/interactionCreate/help.js
module/event/ready/command.js
module/function/slashcommand/5000.js
module/function/slashcommand/math.js
package-lock.json
package.json

- math追加
- 翻訳修正
- バグ修正
- その他調整

機能追加・その他修正

---

module/function/slashcommand/status.js

style:await追加

---

file/commandlist.json
lang/ja.json
module/function/slashcommand/export.js
module/function/slashcommand/follow.js
module/function/slashcommand/guideline.js
module/function/slashcommand/hiroyuki.js
module/function/slashcommand/invites.js
module/function/slashcommand/kick.js
module/function/slashcommand/mc.js
module/function/slashcommand/moderate.js
module/function/slashcommand/news.js
module/function/slashcommand/npm.js
module/function/slashcommand/qr.js

翻訳追加・その他調整

---

file/commandlist.json
index.js
lang/ja.json
module/event/messageCreate/moderate.js
module/function/globalchat/global.js
module/function/globalchat/reply.js
module/function/globalchat/ugc/send.js
module/function/slashcommand/safeweb.js
module/function/slashcommand/webshot.js
module/lib/spam.js

翻訳の追加・その他調整

---

package-lock.json
package.json

remove:いらないパッケージ削除

---

lang/en.json

change:英語に反映

---

module/lib/spam.js

fix:スパム検知ミス

---

module/event.js
module/event/ready/command.js
module/lib/limit.js
package-lock.json
package.json

微調整・いらないパッケージ削除

---

module/function/command/exec.js
package-lock.json
package.json

不要なパッケージ削除・その他調整

---

module/event/ready/load.js
module/function/slashcommand/status.js
module/lib/cpu.js
package-lock.json
package.json

CPU使用率取得方法変更

---

file/commandlist.json
index.js
module/event/interactionCreate/help.js
module/event/ready/command.js
module/function/slashcommand/activity.js
module/function/slashcommand/ban.js

activityコマンド追加・その他調整

---

module/function/slashcommand/user.js

ユーザーの表示情報追加

---

index.js
module/function/contextmenu/member.js
module/function/slashcommand/server.js
module/function/slashcommand/user.js

表示変更・その他調整

---

module/function/slashcommand/activity.js
module/function/slashcommand/mc.js
module/function/slashcommand/server.js

絵文字を使用するように・ミス修正

---

file/commandlist.json
index.js
module/event.js
module/event/interactionCreate/help.js
module/event/ready/command.js
module/function/slashcommand/panel.js
module/function/slashcommand/poll.js
module/function/slashcommand/random.js

いろいろ調整・random追加・パフォーマンス改善

---

file/commandlist.json
module/event.js
module/event/interactionCreate/help.js
module/event/ready/command.js
module/function/slashcommand/moderate.js
package-lock.json
package.json

モデレート機能改変・パッケージアップデート・その他修正

---

module/event/messageCreate/afk.js
module/function/slashcommand/avatar.js
module/function/slashcommand/ban.js
module/function/slashcommand/emoji.js
module/function/slashcommand/system.js
module/function/slashcommand/user.js

17桁のsnowflakeに対応、avatarが取得できるように

---

file/commandlist.json
module/event/interactionCreate/help.js
module/event/ready/command.js
module/function/contextmenu/miq.js
module/function/slashcommand/button.js
module/function/slashcommand/miq.js

button追加・少し修正

---

module/function/slashcommand/gift.js

fix: ギフト作成上限の修正
